"""Canonical decision model + vectorized evaluator (design-review Appendix A.2).

One canonical representation that every authoring view compiles to and that all
analysis reads:

* :class:`Clause` — ``{field, op, value}`` (a single AND term).
* :class:`FieldRef` / :class:`VarRef` / :class:`LookupRef` / :class:`TransformRef`
  — typed ``set`` values.
* :class:`Rule` — an ``id``, a flat AND of clauses (``when``), a ``set`` action,
  and optional sweep ``source`` provenance.
* :class:`DecisionTable` — an ordered rule list (first match wins) plus an
  optional ``default`` set.
* :class:`Pass` — a named table that runs ``after`` an earlier pass (so a later
  pass may read fields an earlier pass wrote).
* :class:`Decision` — one stage output: a list of ordered passes.

:class:`Matcher` / :class:`MatchRow` are the row-level (``any``-of-rows) form used
by destination matching, sharing the same clause/op vocabulary.

Evaluation is vectorized: per output column, ``np.select`` chooses the first
matching rule's value, unmatched rows fall through to the table default or the
existing value. Identical first-match semantics to the legacy ``RuleSet.apply``.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import pandas as pd

from bikescore.decision.ops import TRANSFORM_FNS, UNARY_OPS, apply_op, match_scalar


class VarResolutionError(KeyError):
    """Raised when a ``$var:`` reference names a variable absent from the
    ``variables`` dict (no stage-declared var and no ``config.variables`` entry).

    A *missing* variable is a configuration error and raises; a variable that is
    *present but ``None``* is the null-injection guard (skips the rule), not an error.
    """


def _require_var(name: str, variables: dict | None) -> object:
    """Look up ``name`` in ``variables``; raise if the key is absent.

    Returns the value (which may be ``None``) when present so callers can apply
    their own null handling.
    """
    variables = variables or {}
    if name not in variables:
        raise VarResolutionError(
            f"$var:{name} is not defined (declare it under config.variables "
            f"or as a stage-provided variable)"
        )
    return variables[name]


# ── Typed set values ──────────────────────────────────────────────────────────
#
# Rule.set maps output column names to typed values.  Typed values let every
# consumer (evaluator, analysis, serializer) dispatch on type rather than
# inspecting ad-hoc dict sigils like {"$var": ...}.


@dataclass(frozen=True)
class FieldRef:
    """Read another dataframe column as a rule ``set`` value.

    Used by ``first_non_null`` chain views to copy one column to another.
    """

    field: str


@dataclass(frozen=True)
class VarRef:
    """Resolve a runtime config variable as a rule ``set`` value.

    The evaluator looks up ``name`` in the ``variables`` dict passed to
    :meth:`Decision.apply`.  A set-side ``VarRef`` that resolves to ``None``
    assigns ``None`` (a real null assignment); use :class:`CascadeRef` for the
    "fall through when unset" behaviour.  A *missing* (undeclared) variable is a
    configuration error and raises :class:`VarResolutionError`.
    """

    name: str


@dataclass(frozen=True)
class LookupRef:
    """Table-lookup set value (generated by the chain compiler, not yet evaluated).

    ``_resolve_set_value`` raises ``NotImplementedError`` for this type.
    """

    lookup: str
    key: str


@dataclass(frozen=True)
class MapRef:
    """Inline single-key lookup table used as a rule ``set`` value (Phase 35m).

    Maps the value of one ``key`` column through ``table`` to the output value —
    a decision matrix collapsed into a single rule. When ``default`` is ``None``
    the rule only matches rows whose key is present in ``table`` (unmapped rows
    fall through to later rules / the table default, preserving first-match
    semantics); a non-``None`` ``default`` makes the rule match every row, with
    unmapped keys taking ``default``.
    """

    key: str
    table: Mapping[Any, Any]
    default: Any = None

    def key_mask(self, df: pd.DataFrame) -> pd.Series:
        return _column(df, self.key).isin(list(self.table))


@dataclass(frozen=True)
class TransformRef:
    """Apply a named vectorized transform function as a rule ``set`` value.

    ``fn`` must be a key in :data:`bikescore.decision.ops.TRANSFORM_FNS`;
    validated at parse time.  ``source`` is the input column name in the
    DataFrame.  ``kwargs`` values may themselves be scalars or :class:`VarRef`
    objects (resolved at evaluation time from the ``variables`` dict).
    """

    fn: str
    source: str
    kwargs: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CascadeRef:
    """Cascading-default set value: the first tier that resolves non-null wins.

    Each ``tier`` is itself a parsed set value (commonly a :class:`VarRef`); the
    evaluator coalesces them per row, first-non-null.  A tier that resolves to
    ``None`` (e.g. a ``$var:`` the city never set) is skipped — it does *not*
    drop the rule.  When every tier resolves null the cascade yields null and
    :meth:`DecisionTable.apply` narrows the rule's row mask (like an unmatched
    :class:`MapRef`) so those rows fall through to later rules / the table
    default rather than being pinned to null.
    """

    tiers: tuple[Any, ...]


def _parse_set_value(v: object) -> object:
    """Convert a raw YAML/dict set value to its typed representation."""
    if isinstance(v, dict):
        if "$var" in v:
            return VarRef(str(v["$var"]))
        if "$field" in v:
            return FieldRef(str(v["$field"]))
        if "$lookup" in v:
            if "map" in v:
                return MapRef(
                    key=str(v["$lookup"]),
                    table=dict(v["map"]),
                    default=v.get("default"),
                )
            return LookupRef(lookup=str(v["$lookup"]), key=str(v["key"]))
        if "$cascade" in v:
            return CascadeRef(tuple(_parse_set_value(t) for t in v["$cascade"]))
        if "$apply" in v:
            fn = str(v["$apply"])
            if fn not in TRANSFORM_FNS:
                raise ValueError(
                    f"Unknown transform function '{fn}'. "
                    f"Valid functions: {sorted(TRANSFORM_FNS)}"
                )
            source = str(v["to"])
            kwargs = {
                k: _parse_set_value(val)
                for k, val in v.items()
                if k not in ("$apply", "to")
            }
            return TransformRef(fn=fn, source=source, kwargs=kwargs)
    return v  # scalar (int, float, str, bool, …)


def _serialize_set_value(v: object) -> object:
    """Serialize a typed set value back to the YAML/dict wire format."""
    if isinstance(v, FieldRef):
        return {"$field": v.field}
    if isinstance(v, VarRef):
        return {"$var": v.name}
    if isinstance(v, LookupRef):
        return {"$lookup": v.lookup, "key": v.key}
    if isinstance(v, MapRef):
        d = {"$lookup": v.key, "map": dict(v.table)}
        if v.default is not None:
            d["default"] = v.default
        return d
    if isinstance(v, CascadeRef):
        return {"$cascade": [_serialize_set_value(t) for t in v.tiers]}
    if isinstance(v, TransformRef):
        d: dict = {"$apply": v.fn, "to": v.source}
        d.update({k: _serialize_set_value(val) for k, val in v.kwargs.items()})
        return d
    return v


def _parse_enabled(v: object) -> bool | VarRef:
    """Parse a rule ``enabled`` value: a bool literal, a terse ``$var:NAME`` /
    canonical ``{"$var": NAME}`` reference (→ :class:`VarRef`), or ``None``."""
    if isinstance(v, VarRef):
        return v
    if isinstance(v, str) and v.startswith("$var:"):
        return VarRef(v[len("$var:"):])
    if isinstance(v, dict) and "$var" in v:
        return VarRef(str(v["$var"]))
    return v  # type: ignore[return-value]


def _serialize_enabled(v: bool | VarRef) -> object:
    return {"$var": v.name} if isinstance(v, VarRef) else v


# ── Clause ────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class Clause:
    """A single predicate on one field: ``field op value`` (NaN-safe).

    ``value`` is ``None`` for the unary ops (``present``/``absent``/``is_null``).
    For ``in``/``not_in`` it is a list; for the rest a scalar.
    """

    field: str
    op: str
    value: Any = None

    def mask(self, df: pd.DataFrame, variables: dict[str, Any] | None = None) -> pd.Series:
        col = _column(df, self.field)
        value = self.value
        if isinstance(value, VarRef):
            value = _require_var(value.name, variables)
        return apply_op(self.op, col, value)

    def matches(self, tags: Mapping[str, Any]) -> bool:
        return match_scalar(self.op, tags.get(self.field), self.value)

    def to_dict(self) -> dict:
        d: dict[str, Any] = {"field": self.field, "op": self.op}
        if self.op not in UNARY_OPS:
            d["value"] = list(self.value) if isinstance(self.value, tuple) else self.value
        return d

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> Clause:
        return cls(field=d["field"], op=d["op"], value=d.get("value"))


def _is_numlike(value: Any) -> bool:
    if isinstance(value, (FieldRef, VarRef, LookupRef, TransformRef, MapRef, CascadeRef)):
        return False
    if isinstance(value, pd.Series):
        return pd.api.types.is_numeric_dtype(value) and not pd.api.types.is_bool_dtype(value)
    if value is None:
        return False
    if isinstance(value, bool):
        return False
    if isinstance(value, float) and np.isnan(value):
        return True
    return isinstance(value, (int, float))


def _select_first_match(
    conditions: list[pd.Series],
    values: list[Any],
    fallback: Any,
    index: pd.Index,
) -> Any:
    """First-match selection, dtype-safe.

    Homogeneous numeric values + fallback use ``np.select`` (typed int/float
    output). Anything involving strings / ``None`` falls back to a sequential
    object-dtype fill that preserves ``None`` (so e.g. an unmatched
    ``functional_class`` stays ``None`` for the SQL ``DELETE`` row-drop, not NaN).
    """
    numeric = all(_is_numlike(v) for v in values) and _is_numlike(fallback)
    if not conditions:
        if numeric and not isinstance(fallback, pd.Series):
            return pd.Series(fallback, index=index, dtype="float64")
        return fallback if isinstance(fallback, pd.Series) else pd.Series(
            [fallback] * len(index), index=index, dtype=object
        )
    if numeric:
        return np.select(conditions, values, default=fallback)
    assigned = np.zeros(len(index), dtype=bool)
    result = np.empty(len(index), dtype=object)
    for mask, value in zip(conditions, values):
        m = np.asarray(mask) & ~assigned
        if not m.any():
            continue
        if isinstance(value, pd.Series):
            result[m] = value.to_numpy(dtype=object)[m]
        else:
            result[m] = value
        assigned |= m
    rest = ~assigned
    if rest.any():
        if isinstance(fallback, pd.Series):
            result[rest] = fallback.to_numpy(dtype=object)[rest]
        else:
            result[rest] = fallback
    return pd.Series(result, index=index, dtype=object)


def _resolve_set_value(
    value: Any,
    df: pd.DataFrame,
    variables: dict[str, Any] | None = None,
) -> Any:
    """Resolve a typed rule ``set`` value to a scalar or Series for ``np.select``.

    * :class:`FieldRef` — reads the named column from ``df``.
    * :class:`VarRef` — looks up the variable in ``variables``; returns the
      value, which may be ``None`` (a set-side null assigns null).
    * :class:`CascadeRef` — coalesces its tiers first-non-null (null tiers
      skipped); all-null yields a null Series and the rule mask is narrowed in
      :meth:`DecisionTable.apply` so those rows fall through.
    * :class:`LookupRef` — not yet implemented; raises ``NotImplementedError``.
    * :class:`TransformRef` — applies a vectorized transform function to a
      source column; requires DataFrame context (raises ``NotImplementedError``
      in scalar/trace context).
    * Scalars pass through as-is.
    """
    if isinstance(value, FieldRef):
        return _column(df, value.field)
    if isinstance(value, VarRef):
        return _require_var(value.name, variables)
    if isinstance(value, CascadeRef):
        if not isinstance(df, pd.DataFrame):
            raise NotImplementedError("CascadeRef requires vectorized context")
        resolved_tiers = [
            _resolve_set_value(t, df, variables=variables) for t in value.tiers
        ]
        result: pd.Series | None = None
        for rt in resolved_tiers:
            tier = (
                rt if isinstance(rt, pd.Series)
                else pd.Series([rt] * len(df.index), index=df.index, dtype=object)
            )
            result = tier if result is None else result.where(result.notna(), tier)
        if result is None:
            result = pd.Series(np.nan, index=df.index, dtype=object)

        def _nullish(x: Any) -> bool:
            return x is None or (isinstance(x, float) and np.isnan(x))

        nonnull = [rt for rt in resolved_tiers if not _nullish(rt)]
        if nonnull and all(_is_numlike(rt) for rt in nonnull):
            result = pd.to_numeric(result, errors="coerce")
        return result
    if isinstance(value, MapRef):
        if not isinstance(df, pd.DataFrame):
            raise NotImplementedError("MapRef requires vectorized context")
        col = _column(df, value.key)
        mapped = col.map(value.table)
        if value.default is not None:
            mapped = mapped.where(col.isin(list(value.table)), value.default)
        numeric = all(_is_numlike(x) for x in value.table.values()) and (
            value.default is None or _is_numlike(value.default)
        )
        if numeric:
            mapped = pd.to_numeric(mapped, errors="coerce")
        return mapped
    if isinstance(value, LookupRef):
        raise NotImplementedError(f"LookupRef evaluation is not yet implemented: {value!r}")
    if isinstance(value, TransformRef):
        if not isinstance(df, pd.DataFrame):
            raise NotImplementedError("TransformRef requires vectorized context")
        from bikescore.decision.ops import TRANSFORM_FNS as _TFN
        fn = _TFN[value.fn]
        resolved_kwargs = {
            k: ((variables or {}).get(kv.name) if isinstance(kv, VarRef) else kv)
            for k, kv in value.kwargs.items()
        }
        series = _column(df, value.source)
        return fn(series, **resolved_kwargs)
    return value


def _column(df: pd.DataFrame, name: str) -> pd.Series:
    """Return the named column, or an all-NaN object Series when absent.

    Absent optional OSM-tag columns therefore behave as missing values: ``eq``/
    ``in`` are False, ``is_null``/``absent`` are True — matching the legacy
    engine for the conditions the default rules actually use.
    """
    if name in df.columns:
        return df[name]
    return pd.Series(np.nan, index=df.index, dtype=object)


def _flatten_set_value(v: Any) -> list[Any]:
    """A set value plus, for a :class:`CascadeRef`, its nested tiers (recursively).

    Lets ``referenced_fields`` / ``referenced_variables`` see refs buried in cascade
    tiers (so the 35h/35i gates cover them)."""
    if isinstance(v, CascadeRef):
        out: list[Any] = []
        for t in v.tiers:
            out.extend(_flatten_set_value(t))
        return out
    return [v]


# ── Rule + table ──────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class Rule:
    """An ``id``, a flat AND of clauses (``when``), and a ``set`` action.

    ``source`` records sweep provenance — ``{"id": <authored id>, "vars": {...}}``
    — so analysis can aggregate expanded rules back to the authored rule.
    """

    id: str
    when: tuple[Clause, ...]
    set: Mapping[str, int | float | str | bool | FieldRef | VarRef | LookupRef | TransformRef | CascadeRef | None]
    source: Mapping[str, Any] | None = None
    enabled: bool | VarRef = True

    def row_mask(
        self, df: pd.DataFrame, variables: dict[str, Any] | None = None
    ) -> pd.Series:
        mask = pd.Series(True, index=df.index)
        for clause in self.when:
            mask &= clause.mask(df, variables)
        return mask

    def matches(self, tags: Mapping[str, Any]) -> bool:
        return all(c.matches(tags) for c in self.when)

    def referenced_fields(self) -> set[str]:
        fields = {c.field for c in self.when}
        for v in self.set.values():
            for ref in _flatten_set_value(v):
                if isinstance(ref, FieldRef):
                    fields.add(ref.field)
                if isinstance(ref, TransformRef):
                    fields.add(ref.source)
                if isinstance(ref, MapRef):
                    fields.add(ref.key)
        return fields

    def referenced_variables(self) -> set[str]:
        """Config ``$var:`` names this rule references (predicate- and set-side).

        Mirrors :meth:`referenced_fields` for variables: a ``VarRef`` on a ``when``
        clause value (predicate-side, resolved via ``_require_var``) and as a ``set``
        value or a ``TransformRef`` kwarg (set-side). Drives the resolve-time
        undeclared-variable gate (Phase 35h).
        """
        names: set[str] = set()
        for c in self.when:
            if isinstance(c.value, VarRef):
                names.add(c.value.name)
        for v in self.set.values():
            for ref in _flatten_set_value(v):
                if isinstance(ref, VarRef):
                    names.add(ref.name)
                if isinstance(ref, TransformRef):
                    for kv in ref.kwargs.values():
                        if isinstance(kv, VarRef):
                            names.add(kv.name)
        if isinstance(self.enabled, VarRef):
            names.add(self.enabled.name)
        return names

    def is_enabled(self, variables: dict[str, Any] | None = None) -> bool:
        """Whether this rule contributes (Phase 36b ``enabled`` gate).

        Literal bool → itself; :class:`VarRef` → its value in ``variables``
        (absent ⇒ ``None``); ``None`` ⇒ disabled; any other type raises
        ``ConfigValidationError`` (no truthiness coercion)."""
        e: Any = self.enabled
        if isinstance(e, VarRef):
            e = (variables or {}).get(e.name)
        if e is None:
            return False
        if e is True or e is False:
            return e
        from bikescore.config import ConfigValidationError
        raise ConfigValidationError(
            f"rule {self.id!r} 'enabled' must be a boolean or a $var: reference; "
            f"got {e!r}"
        )

    def to_dict(self) -> dict:
        d: dict[str, Any] = {
            "id": self.id,
            "when": [c.to_dict() for c in self.when],
            "set": {k: _serialize_set_value(v) for k, v in self.set.items()},
        }
        if self.source:
            d["source"] = dict(self.source)
        if self.enabled is not True:
            d["enabled"] = _serialize_enabled(self.enabled)
        return d

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> Rule:
        return cls(
            id=d["id"],
            when=tuple(Clause.from_dict(c) for c in d.get("when", [])),
            set={k: _parse_set_value(v) for k, v in d.get("set", {}).items()},
            source=d.get("source"),
            enabled=_parse_enabled(d.get("enabled", True)),
        )


@dataclass
class DecisionTable:
    """An ordered rule list (first match wins) + optional ``default`` set."""

    rules: list[Rule] = field(default_factory=list)
    default: dict[str, Any] | None = None

    def output_fields(self) -> list[str]:
        cols: list[str] = []
        for rule in self.rules:
            for c in rule.set:
                if c not in cols:
                    cols.append(c)
        for c in self.default or {}:
            if c not in cols:
                cols.append(c)
        return cols

    def referenced_fields(self) -> set[str]:
        out: set[str] = set()
        for rule in self.rules:
            out |= rule.referenced_fields()
        return out

    def referenced_variables(self) -> set[str]:
        out: set[str] = set()
        for rule in self.rules:
            out |= rule.referenced_variables()
        return out

    def apply(
        self,
        df: pd.DataFrame,
        variables: dict[str, Any] | None = None,
    ) -> pd.DataFrame:
        """Apply this table to ``df`` (returns a copy).

        For each output column, evaluate rule masks in order and pick the first
        match via ``np.select``; the fallthrough is the table ``default`` for
        that column, else the column's existing value, else NaN.

        *variables* maps ``{name}`` placeholders in ``set:`` values to config
        scalars.  Rules whose placeholder resolves to ``None`` are skipped
        (null-injection guard).
        """
        if not self.rules and not self.default:
            return df.copy()
        df = df.copy()
        default_set = self.default or {}
        # Phase 36b: a disabled rule contributes no branch to any column. Evaluate
        # the ``enabled`` gate once, then iterate the active rules per column.
        active = [r for r in self.rules if r.is_enabled(variables)]
        for col in self.output_fields():
            conditions: list[pd.Series] = []
            values: list[Any] = []
            for rule in active:
                if col not in rule.set:
                    continue
                set_value = rule.set[col]
                resolved = _resolve_set_value(set_value, df, variables=variables)
                mask = rule.row_mask(df, variables)
                if isinstance(set_value, MapRef) and set_value.default is None:
                    mask = mask & set_value.key_mask(df)
                elif isinstance(set_value, CascadeRef):
                    # Rows where every tier resolved null fall through to later
                    # rules / the table default (no null pinning).
                    mask = mask & resolved.notna()
                conditions.append(mask)
                values.append(resolved)
            if col in default_set:
                fallback: Any = default_set[col]
            elif col in df.columns:
                fallback = df[col]
            else:
                fallback = np.nan
            df[col] = _select_first_match(conditions, values, fallback, df.index)
        return df

    def to_dict(self) -> dict:
        d: dict[str, Any] = {"rules": [r.to_dict() for r in self.rules]}
        if self.default is not None:
            d["default"] = dict(self.default)
        return d

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> DecisionTable:
        return cls(
            rules=[Rule.from_dict(r) for r in d.get("rules", [])],
            default=dict(d["default"]) if d.get("default") is not None else None,
        )


# ── Pass + decision ───────────────────────────────────────────────────────────

@dataclass
class Pass:
    """A named decision table that runs ``after`` an earlier pass (if set)."""

    name: str
    table: DecisionTable
    after: str | None = None

    def to_dict(self) -> dict:
        d: dict[str, Any] = {"name": self.name, "table": self.table.to_dict()}
        if self.after:
            d["after"] = self.after
        return d

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> Pass:
        return cls(
            name=d["name"],
            table=DecisionTable.from_dict(d["table"]),
            after=d.get("after"),
        )


@dataclass
class Decision:
    """One stage output expressed as an ordered list of passes.

    Passes run in declared order (already topologically sorted at load time by
    ``after:``); a later pass reads fields earlier passes wrote.
    """

    name: str
    passes: list[Pass] = field(default_factory=list)

    # ── Evaluation ────────────────────────────────────────────────────────────

    def apply(
        self,
        df: pd.DataFrame,
        variables: dict[str, Any] | None = None,
    ) -> pd.DataFrame:
        """Run every pass in order. Derived fields must already be materialized
        (see :func:`bikescore.decision.catalog.run_decision`)."""
        for p in self.passes:
            df = p.table.apply(df, variables=variables)
        return df

    def referenced_fields(self) -> set[str]:
        out: set[str] = set()
        for p in self.passes:
            out |= p.table.referenced_fields()
        return out

    def referenced_variables(self) -> set[str]:
        out: set[str] = set()
        for p in self.passes:
            out |= p.table.referenced_variables()
        return out

    def output_fields(self) -> list[str]:
        cols: list[str] = []
        for p in self.passes:
            for c in p.table.output_fields():
                if c not in cols:
                    cols.append(c)
        return cols

    def max_output_value(self, columns: Iterable[str]) -> int:
        """Maximum integer value any rule/default assigns to any of ``columns``.

        Used by ``StressConfig.n_levels`` to infer the stress model range.
        """
        cols = set(columns)
        values: list[int] = []
        for p in self.passes:
            for rule in p.table.rules:
                for col, v in rule.set.items():
                    if col not in cols:
                        continue
                    if isinstance(v, int) and not isinstance(v, bool):
                        values.append(v)
                    elif isinstance(v, MapRef):
                        values.extend(
                            x for x in v.table.values()
                            if isinstance(x, int) and not isinstance(x, bool)
                        )
            for col, v in (p.table.default or {}).items():
                if col in cols and isinstance(v, int) and not isinstance(v, bool):
                    values.append(v)
        return max(values, default=1)

    # ── Serialization ─────────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {"name": self.name, "passes": [p.to_dict() for p in self.passes]}

    def to_yaml(self) -> str:
        import yaml

        return yaml.dump(self.to_dict(), sort_keys=False, allow_unicode=True)


    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> Decision:
        return cls(
            name=d.get("name", ""),
            passes=[Pass.from_dict(p) for p in d.get("passes", [])],
        )


# ── Matcher (row-level any-of-rows) ──────────────────────────────────────────

@dataclass(frozen=True)
class MatchRow:
    """A flat AND of clauses, evaluated against an OSM tag mapping."""

    clauses: tuple[Clause, ...]

    def matches(self, tags: Mapping[str, Any]) -> bool:
        return all(c.matches(tags) for c in self.clauses)

    def referenced_fields(self) -> set[str]:
        return {c.field for c in self.clauses}

    def to_dict(self) -> dict:
        return {"all": [c.to_dict() for c in self.clauses]}

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> MatchRow:
        clauses = d.get("all", d.get("clauses", []))
        return cls(clauses=tuple(Clause.from_dict(c) for c in clauses))


@dataclass(frozen=True)
class Matcher:
    """A boolean membership predicate: ``any`` of conjunction rows (A.6.6).

    The *one* place OR lives. ``rows[0]`` is the primary row (destinations use it
    to bypass the polygon-cluster check, per the SQL precedence quirk).
    """

    rows: tuple[MatchRow, ...] = ()

    def matches(self, tags: Mapping[str, Any]) -> bool:
        return any(r.matches(tags) for r in self.rows)


    def referenced_fields(self) -> set[str]:
        out: set[str] = set()
        for r in self.rows:
            out |= r.referenced_fields()
        return out

    def __bool__(self) -> bool:
        return bool(self.rows)

    def to_dict(self) -> dict:
        return {"any": [r.to_dict() for r in self.rows]}

    @classmethod
    def from_dict(cls, d: Mapping[str, Any] | None) -> Matcher:
        if not d:
            return cls(())
        rows = d.get("any", [])
        return cls(rows=tuple(MatchRow.from_dict(r) for r in rows))
